spring:
  application:
    name: 'countries'
    version: "1.0"
  datasource:
    url: jdbc:postgresql://localhost:5432/qa_guru
    username: postgres
    password: example
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 10000
      max-lifetime: 1800000
      auto-commit: true
      schema: qa_guru
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform:
    show-sql: false
    generate-ddl: true
    open-in-view: false
  flyway:
    enabled: true                    # ???????? Flyway (?? ????????? ? true)
    baseline-on-migrate: true  # ??????? ??? ??????????? ? ???????????? ??
    clean-disabled: true             # ????????? `clean` ? ??????????!
    baseline-version: 0
    schemas: qa_guru
    locations: classpath:db/migration/countries
server:
  port: 8585